on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    env:
      VITE_APPWRITE_URL: ${{ secrets.VITE_APPWRITE_URL }}
      VITE_APPWRITE_PROJECT_ID: ${{ secrets.VITE_APPWRITE_PROJECT_ID }}
      VITE_APPWRITE_DATABASE_ID: ${{ secrets.VITE_APPWRITE_DATABASE_ID }}
      VITE_APPWRITE_COLLECTION_ID: ${{ secrets.VITE_APPWRITE_COLLECTION_ID }}
      VITE_APPWRITE_BUCKET_ID: ${{ secrets.VITE_APPWRITE_BUCKET_ID }}
      VITE_APPWRITE_CATEGORY_COLLECTION_ID: ${{ secrets.VITE_APPWRITE_CATEGORY_COLLECTION_ID }}
      VITE_APPWRITE_CATEGORY_DOCUMENT_ID: ${{ secrets.VITE_APPWRITE_CATEGORY_DOCUMENT_ID }}
      VITE_APPWRITE_FAQS_COLLECTION_ID: ${{ secrets.VITE_APPWRITE_FAQS_COLLECTION_ID }}
      VITE_APPWRITE_FAQS_DOCUMENT_ID: ${{ secrets.VITE_APPWRITE_FAQS_DOCUMENT_ID }}
      VITE_QUERY_COLLECTION_ID: ${{ secrets.VITE_QUERY_COLLECTION_ID }}
      VITE_QUERY_DOCUMENT_ID: ${{ secrets.VITE_QUERY_DOCUMENT_ID }}
      VITE_ACCESSIBILITY_COLLECTION_ID: ${{ secrets.VITE_ACCESSIBILITY_COLLECTION_ID }}
      VITE_TINY_MCE_API_KEY: ${{ secrets.VITE_TINY_MCE_API_KEY }}
      
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      
    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
        username: ${{ secrets.GIT_CPANEL_REACT_USER }}
        password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
        protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
        local-dir: ./dist/
